<a href="https://colab.research.google.com/github/rajeshdchikkala/Ai-Datascience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
sales = np.array([1000,2000,3000,4000])
print(sales)

[1000 2000 3000 4000]

In [3]:
sales.dtype

dtype('int64')

In [4]:
sales = np.array([1000.89,2000,3000,4000])
print(sales)

[1000.89 2000.   3000.   4000.  ]

In [5]:
sales-500

array([ 500.89, 1500.  , 2500.  , 3500.  ])

In [6]:
sales*2

array([2001.78, 4000.  , 6000.  , 8000.  ])

In [9]:
arr_zeroes = np.zeros((2,3))
print(arr_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]

In [10]:
arr_ones = np.ones((2,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]

In [11]:
arr_arange=np.arange(0,10,2)
print(arr_arange)

[0 2 4 6 8]

In [13]:
arr_arange=np.arange(10,0,-1)
print(arr_arange)

[10  9  8  7  6  5  4  3  2  1]

In [15]:
arr_arange=np.arange(0,15,3)
print(arr_arange)

[ 0  3  6  9 12]

In [16]:
arr_arange=np.arange(0,15)
print(arr_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

In [17]:
arr_linspace = np.linspace(0,10,num =5)
print(arr_linspace)

[ 0.   2.5  5.   7.5 10. ]

In [18]:
arr_linspace = np.linspace(0,10,num =2)
print(arr_linspace)

[ 0. 10.]

In [19]:
arr_linspace = np.linspace(0,10,num =3)
print(arr_linspace)

[ 0.  5. 10.]

In [22]:
arr_linspace = np.linspace(0,10,num =4)
print(arr_linspace)
#it will be giving spacing values between two numbers where 0 is initial number and 10 is end of range and num=3 is spacing number

[ 0.          3.33333333  6.66666667 10.        ]

In [23]:
arra_1d =np.array([1,2,3,4,5,6])
arra_2d =np.reshape(arra_1d,(2,3))
print(arra_2d)

[[1 2 3]
 [4 5 6]]

In [27]:
arra_1d =np.array([1,2,3,4,5,6,7,8])
arra_2d =np.reshape(arra_1d,(2,4))
print(arra_2d)

[[1 2 3 4]
 [5 6 7 8]]

In [30]:
arr_linspace = np.linspace(0,10,num =4,endpoint=False,dtype='int')
print(arr_linspace)

[0 2 5 7]

In [31]:
arra_1d =np.array([1,2,3])
arra_2d =np.array([1,2,3])
arr_sum =np.add(arra_1d,arra_2d)
print(arr_sum)

[2 4 6]

In [35]:
arra_1d =np.array([[1,2,3],[4,5,6]])
s=np.sum(arra_1d)
print(s)
s
#sum is going to add all elements in array

21

np.int64(21)

In [36]:
arra_1d =np.array([1,2,3])
s=np.sum(arra_1d)
print(s)

6

In [37]:
arra_1d =np.array([[1,2,3],[4,5,6]])
s=np.mean(arra_1d)
print(s)

3.5

In [38]:
arra_1d =np.array([1,2,3])
s=np.mean(arra_1d)
print(s)

2.0

In [41]:
import pandas as pd
import numpy as np
import csv

In [42]:
wd = {
    'day' : ['1/1/2017','1/2/2017','1/3/2017','1/4/2017'],
    'temperature' : [32,35,28,24],
    'windspeed' :[6,7,2,7],
    'event': ['Rain','Sunny','Snow','Rain']
}
df = pd.DataFrame(wd)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Rain

In [43]:
df.to_csv("weather.csv",index=False)
#index =flase is we dont want index in csv file

In [44]:
data = pd.read_csv("weather.csv")
data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Rain

In [45]:
data.shape

(4, 4)

In [46]:
type(data)

pandas.core.frame.DataFrame

In [48]:
row,col=data.shape

In [49]:
row

4

In [50]:
col

4

In [51]:
df.head

<bound method NDFrame.head of         day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Rain>

In [52]:
df.head(4)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Rain

In [53]:
df.head(3)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [55]:
df.tail(2)

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Rain